version: 2.1
jobs:
  Run-Tests:
    docker:
      - image: bitwalker/alpine-elixir-phoenix:1.10.2
    steps:
      - checkout
      - run:
          name: Run Tests
          working_directory: ocean
          command: |
            MIX_ENV=test mix deps.get
            MIX_ENV=test mix test

  Build-Release:
    docker:
      - image: bitwalker/alpine-elixir-phoenix:1.10.2
    steps:
      - checkout
      - run:
          name: Build Release
          working_directory: ocean
          command: |
            mix deps.get --only prod
            MIX_ENV=prod mix compile
            npm install --prefix ./assets
            npm run deploy --prefix ./assets
            MIX_ENV=prod mix phx.digest
            MIX_ENV=prod mix release
      - run:
          name: Persist Built Release
          command: |
            mkdir -p /tmp/workspace/releases
            mv ./ocean/_build/prod/rel/ocean/bin/ocean /tmp/workspace/releases
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - releases

  Deploy-To-Droplet:
    docker:
      - image: bitwalker/alpine-elixir-phoenix:1.10.2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          command: | 
            scp -o StrictHostKeyChecking=no -r /tmp/workspace/releases/ocean root@178.128.155.192.com://home/root/

workflows:
  version: 2.1
  Deploy_Workflow:
    jobs:
      - Run-Tests
      - Build-Release:
          requires:
            - Run-Tests
      - Wait-Approval:
          type: approval
          requires:
            - Build-Release
      - Deploy-To-Droplet:
          requires:
            - Wait-Approval