version: 2.1
jobs:
  build:
    docker:
      - image: bitwalker/alpine-elixir-phoenix:1.10.2
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Ocean Tests
          command: |
            cd ocean
            MIX_ENV=test mix deps.get
            MIX_ENV=test mix test

