version: 2.1
jobs:
  Run-Tests:
    docker:
      - image: bitwalker/alpine-elixir-phoenix:1.10.2
    steps:
      - checkout
      - run:
          command: |
            cd ocean
            echo "Fetching Dependencies"
            MIX_ENV=test mix deps.get
            echo "Running Tests"
            MIX_ENV=test mix test

  Deploy:
    docker:
      - image: bitwalker/alpine-elixir-phoenix:1.10.2
    steps:
      - checkout
      - run:
          command: echo "This Worked!!"

workflows:
  version: 2.1
  Deploy_Workflow:
    jobs:
      - Run-Tests
      - Hold-For-Approval:
          type: approval
          requires:
            - Run-Tests
      - Deploy:
          requires:
            - Hold-For-Approval